language: ruby
rvm:
- 1.8.7
- 2.0.0
script: bundle exec rake spec
branches:
  only:
  - master
  - "/^issues\\/.*$/"
  - dev
notifications:
  email:
  - arusso@berkeley.edu
  slack:
    secure: JcrSCjg9bLNPICfRuUyXbPh+BwkYc8MMVDSk59ALBDeR/wjOKKBsyjsgfHvjtC9CADSCjOg8nG5IdIyUG0I4oshsj3m7iVDiMOddvmAfvteNEYEbLe14W0FTtBO4SoSTy7g42bC4T6wGZF2cWlmYxaA7KDCmzXH1LX7qVWA7iWs=
env:
- PUPPET_VERSION="~> 2.7.0"
- PUPPET_VERSION="~> 3.8.0"
matrix:
  exclude:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  include:
  - rvm: 1.8.7
    env:
    - PUPPET_VERSION="~> 3.8.0"
    - PARSER="future"
  - rvm: 2.0.0
    env:
    - PUPPET_VERSION="~> 3.8.0"
    - PARSER="future"
